/**
 * Runtime bindings this Worker declares in wrangler.jsonc.
 *
 * OpenNext declares `CloudflareEnv` as an open interface precisely so apps can
 * add their own bindings here. Hand-written rather than generated by
 * `wrangler types` so the repo does not depend on `@cloudflare/workers-types`,
 * whose global declarations conflict with the DOM and Node types Next already
 * compiles against.
 */
declare global {
  interface CloudflareEnv {
    /** Workers AI. See lib/server/workers-ai.ts — the only consumer. */
    AI?: {
      run(model: string, inputs: Record<string, unknown>): Promise<unknown>;
    };
  }
}

export {};
